name: Build

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
        
jobs:
  version:
    name: Versions
    uses: newcross-tech/workflows/.github/workflows/getVersion.yaml@master
    with:
      toolset: node|gradle
      prefix:
      pr_number:
      input_file:
      base_version: 



  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Complete other build tasks here....




  docker:
    name: Docker image
    needs:
      - build
      - version
    uses: newcross-tech/workflows/.github/workflows/docker.yaml@master
    with:
      ecr-repository: ""
      push-images: ${{ github.ref_name == 'master' || github.ref_name == 'develop' }}
      file: ./Dockerfile
      context: .
      image-tag: ${GITHUB_REF##*/}-${{ needs.version.outputs.IMAGE_TAG }}
      tag-latest: ${{ github.ref_name == 'main' }} 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


