
name: Deploy master branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  prod-workflow:
    uses: ./.github/workflows/build.yaml
    with:
      stage: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      