
name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  dev-workflow:
    uses: ./.github/workflows/build.yaml
    with:
      stage: develop
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SBX }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SBX }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}